### ISSUE TITLE
Sentry sourcemaps are broken

### ISSUE THREAD

**Issue by floatplane** [NWACus/avy#590] opened 2023-11-27 21:22 UTC
https://github.com/NWACus/avy/pull/532 started using the bundle update date/time as the `release` parameter for Sentry and PostHog. This approach generally makes sense, except that the Expo/Sentry sourcemap uploader doesn't know that we're using a custom release string and so the sourcemaps disappear.

Fixing this might be slightly gnarly? Or at least it will need to be tested and tweaked until it's right. 

I think having a monotonically increasing release based on JS bundle build date is still a useful concept. It probably just needs something like the following:

1. Instead of building a version string from the Expo publish date at runtime [0], generate that version string (e.g. `2023.11.27.21.11`) in the shell and export it as `EXPO_PUBLIC_SENTRY_RELEASE`. Use something like this (works on OS X, not sure if Linux is different):
```
$ date -u +"%Y.%m.%d.%H.%m"
2023.11.27.21.11
```
2. Modify the postPublish hook in app.config.ts to set the Sentry release to `EXPO_PUBLIC_SENTRY_RELEASE` [1]
3. Modify the `Sentry.init` call in App.tsx to pass `EXPO_PUBLIC_SENTRY_RELEASE` for `release`
4. Remove `dist` from the `Sentry.init` arguments in App.tsx - the default behavior will use the build number, and those will stay in sync automatically

References
[0] https://github.com/NWACus/avy/blob/967bf8a6daa892777e87707d8a315a2842859082/hooks/useEASUpdateStatus.ts#L25-L28
[1] https://docs.expo.dev/guides/using-sentry/
[2] https://docs.sentry.io/platforms/react-native/sourcemaps/

**Comment by stevekuznetsov** [comment] 2023-11-27 21:33
Can we use the commit SHA instead of a synthetic version we compute "the same way" when we're updating the source maps?

**Comment by floatplane** [comment] 2023-11-27 22:10
I don't think you can use a SHA. I believe Sentry wants `release` to be something that is version shaped (`x.y.z`) so that it knows how to order reports and flag regressions. Without that ordering, you can't mark an error as "fixed in the next version, bring it back to me if that's not the case". 

Default Expo behavior was to use app binary version (`1.0.4`), which is pretty useless when trying to distinguish OTA versions.

**Comment by stevekuznetsov** [comment] 2023-11-28 00:25
Gotcha. The other thing that I've seen many projects do is to tag (at the `git` level) the major releases, and then use the count of ancestor commits as the Z stream - should be a monotonically increasing number on top of the original version, and still remains 1:1 with commits so we eliminate any possibility of weird domain mismatches in version generation.

**Comment by floatplane** [comment] 2023-11-28 01:55
That could work. Personally I like the ergonomics of a date-based format - very easy to look at a bug report (either in Sentry or just someone sending email) and say "oh, they're not running the correct version, we fixed that a day later". But if you want release strings to look more like `1.0.4.x` then that's reasonable too!

It's maybe simpler to just tag all the releases, as opposed to making humans count # of commits from a base tag [0]? It's not like there are _that_ many releases, either binary or OTA. Might be nicer for quick investigations, i.e. run `git lol 1.0.4.47` to quickly browse commit history for a given release. 

Still, the most important thing is to make sure the same release string is used for Sentry and displayed in the About page, I should think. If you don't have that then you'll go crazy 😄 

[0] (even if it's running a script to do so, it just feels like an extra hurdle)

**Comment by stevekuznetsov** [comment] 2023-11-28 02:16
Looking at [their docs](https://docs.sentry.io/platforms/react-native/configuration/releases/?original_referrer=https%3A%2F%2Fgithub.com%2FNWACus%2Favy%2Fissues%2F590#bind-the-version) it looks like we can use the SHA itself. Hard to use their doc search for either "regression detection" or "release:latest" but we're really not Sentry super-users so /shrug

**Comment by floatplane** [comment] 2023-11-28 04:56
I wouldn't call myself a super-user, but I do use "Resolved in the next release" when clearing errors out of the queue (and I expect the error to be re-awakened if it occurs again in the next release, or some release after that). That seems like pretty much the most basic Sentry activity, actually. I can't tell if that breaks with a SHA? 

<img width="265" alt="image" src="https://github.com/NWACus/avy/assets/101196/606aa89e-f89e-4970-a0d3-13e796bf0dd4">

It is funny that they note that it's non-semver - that's probably a reasonable argument for getting on the happy path and passing a more traditional release string.

**Comment by stevekuznetsov** [comment] 2023-11-28 14:00
The documentation talks about those features being gated on semver, so if we're already not there, nothing you're using will break. We can use the "resolved in a commit..." button in your screenshot :)

**Closed** 2023-12-26 16:35 UTC
