### ISSUE TITLE
Home sometimes not loading after being open 

### ISSUE THREAD

**Issue by charlotteguard** [NWACus/avy#265] opened 2023-03-28 22:37 UTC
I haven't been able to repro this but a friend sent a screen shot that the map / polygons will occasionally not load if the app has been open in the background for a while. If he force closes the app and reopens it works perfectly. I will gather more info! 
![IMG_1060](https://user-images.githubusercontent.com/119702342/228382167-083008ae-2b01-4841-b094-7a2201db2910.jpg)

**Comment by stevekuznetsov** [comment] 2023-03-29 02:30
@charlotteguard any chance you could get someone who has this happen to them to go to the menu and "email logs" for us? Until we get logs showing up I don't know that we can inspect more.

@floatplane in these cases not showing "what" is being loaded is detrimental to our debugging, even if it's good for UX in most cases - what sorts of patterns have you seen around this issue to keep the UX but to allow debugability?

**Comment by floatplane** [comment] 2023-03-29 14:31
honestly, I think the answer to start with is better/deeper/more logging. I saw the log Charlotte forwarded and it's basically empty 😢.

you could do a simple progress bar where each interval gives you a clue as to where it is in the process, but I don't know if it's going to help much. do you have a suspicion about what might be going on here?

maybe start by adding logging on each render pass through `QueryState` so you know which requests are completed and which requests are still pending? my suspicion is that one of the requests is in a wedged state and needs to be aborted more quickly. have we set an Axios timeout to a reasonable value? according to https://stackoverflow.com/questions/57995863/what-is-axios-default-timeout, Axios requests never timeout by default 😱

**Comment by floatplane** [comment] 2023-03-29 14:37
also, is this a duplicate of #240?

**Comment by charlotteguard** [comment] 2023-03-29 15:00
@stevekuznetsov I asked him to send the logs - is that helpful for us to do when anyone encounters a bug or will it be overburdening? 

@floatplane I haven't actually encountered this specific error but what would help for better/better logging? The log I sent was after I encountered the zoom way out issue but had to force quit the app to click on any buttons. I don't know how the logs work.. re duplicate - seems like it but maybe @stevekuznetsov can confirm.

**Comment by floatplane** [comment] 2023-03-29 15:06
Ahhhh we clear the log on restart so that's why there's nothing to see after a crash/force quit 🙈. I remember I did that so that the logs wouldn't grow without bound. https://github.com/stevekuznetsov/avalanche-forecast/blob/315e572a8b292bcff868d6f4a874bb80a09be116/logger.ts#L6-L15

@stevekuznetsov we could probably get a simple or complicated as we want here, but wdyt about a simple change to only keep 2 log files - the current run and the previous run - and emailing both of those from the debug menu.

**Comment by yuliadub** [comment] 2023-03-29 17:05
I have been seeing this a lot as well :( where the app is not loading, usually when I try to open it when its been running in the background for a while and I havent interacted with it since I first opened it (usually 3+hours)

**Comment by stevekuznetsov** [comment] 2023-03-29 17:20
I think a small hot-fix to rotate through two files and send both is likely a good band-aid for now but I'd love to spend time setting up a central logging exporting to a persistent system so that we don't need to manage rotation on our end and users don't need to remember to send us things.

**Comment by floatplane** [comment] 2023-09-20 23:42
@charlotteguard I haven't seen this so I'm going to close it, but feel free to re-open if it pops up again?

**Closed by floatplane** 2023-09-20 23:42 UTC
