### ISSUE TITLE
Observation Count Not In Proper English

### ISSUE THREAD

**Issue by stevekuznetsov** [NWACus/avy#357] opened 2023-09-20 21:19 UTC
![File (12)](https://github.com/NWACus/avy/assets/7328370/bcb8a56c-86c9-44ed-95f2-93d4423ab3c6)

"0 observation"

cc @floatplane

**Comment by floatplane** [comment] 2023-09-20 23:19
really a duplicate of #329

**Comment by floatplane** [comment] 2023-09-22 21:37
fixed

**Closed by floatplane** 2023-09-22 21:37 UTC
